### ISSUE TITLE
Error importing this project with Intellij 2019.2 Community

### ISSUE THREAD

**Issue by catluc** [jarroyoesp/KotlinMultiplatform_MVVM#1]
The error looks like that, and project cant be imported
10:33	Duplicate content roots detected
			Path [C:/Users/Default/Documents/KotlinMultiplatform_MVVM-master/SharedCode/src/androidTest/kotlin] of module [SharedCode_androidAndroidTest] was removed from modules [SharedCode_androidTest]
			Also 1 more path was deduplicated. See idea log for details

10:34	Duplicate content roots detected
			Path [C:/Users/Default/Documents/KotlinMultiplatform_MVVM-master/SharedCode/src/androidTest/kotlin] of module [SharedCode_androidAndroidTest] was removed from modules [SharedCode_androidTest]
			Also 1 more path was deduplicated. See idea log for details

**Comment by catluc** [comment]
Nevermind, fixed deleting your .idea folder, i guess u have to git .ignore it from your project

**Comment by jarroyoesp** [comment]
Hi @catluc, thank you for your comment. I've just removed .idea folder.
