### ISSUE TITLE
Question: LiveData + lifecycle

### ISSUE THREAD

**Issue by dima-ko** [jarroyoesp/KotlinMultiplatform_MVVM#3]
Hey, Javier. I only see you are using `dev.icerock.moko.mvvm.livedata.LiveData.addObserver()`, but you never do `dev.icerock.moko.mvvm.livedata.LiveData.removeObserver()`. Is it intentional?
If I add `removeObserver()` in `onPause()` and do `addObserver()` in `onResume()`  - do you see any potential memory leaks here? compared to android's `viewmodel.livaData.observe(viewLifecycleOwner, {})`

**Comment by jarroyoesp** [comment]
Hi @dima-ko, thanks for the question. It's something that I have to improve but I always say I have to change it and .... Remove observer in OnPause() could be an option. Other option could be to addObserver in OnCreate() and remove in OnDestroy() but now I am not sure if in some case could the observer remains without be removed.

**Comment by jarroyoesp** [comment]
I've just uploaded a commit improving the issue that you commented. And one thing more, in the viewModels I uses a job, now I've changed it to use viewModelScope and cancel it when it is cleared. Take a look and tell me if you have some question or improvement.

**Comment by dima-ko** [comment]
Hey. Looks great now! I tested it with LeakCanary and see no leaks :)
